INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (1,'Stéphanie Labbé','Canadá',35,1,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (2,'Constance Picaud','Francia',23,2,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (3,'Barbora Votíková','República Checa',25,3,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (4,'Charlotte Voll','Alemania',22,4,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (5,'Paulina Dudek','Polaca',23,5,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (6,'Elisa De Almeida','Francia',23,6,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (7,'Sakina Karchaoui','Francia',25,7,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (8,'Ashley Lawrence','Canadá',26,8,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (9,'Amanda Llestedt','Suecia',28,9,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (10,'Estelle Cascarino','Francia',24,10,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (11,'Jade Le Guilly','Francia',19,11,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (12,'Luana','Brasil',28,12,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (13,'Grace Geyoro','Francia',24,13,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (14,'Sara Däbritz','Alemania ',26,14,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (15,'Kheira Hamraoui','Francia',31,15,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (16,'Laurina Fazer','Francia',18,16,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (17,'Aminata Diallo','Francia',26,17,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (18,'Sandy Baltimore','Francia',21,18,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (19,'Léa Khelifi ','Francia',22,19,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (20,'Marie-Antoinette','Francia',23,20,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (21,'Ramona Bachmann','Suecia',31,21,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (22,'kadidiatou Diani','Francia',26,22,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (23,'Celin Bizet Iidhusoy','Noruega',20,23,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (24,'Jordyn Huitema','Canadá',20,24,'Paris San Germman');
INSERT INTO jugador(`id`,`Nombre`,`País`,`Edad`,`Especialidad_id`,`Equipo`) VALUE (25,'Hawa Sangaré','Francia',19,25,'Paris San Germman');